# Optional autoscaling example for local learning.
# Metrics require a metrics server. In Minikube: minikube addons enable metrics-server
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: woki-brain
  namespace: k8s-local
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: woki-brain
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
